# Generated by Django 5.1.5 on 2025-01-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='currency',
            field=models.CharField(choices=[('usd', 'usd'), ('eur', 'eur'), ('gbp', 'gbp'), ('pln', 'pln')], default=('usd', 'usd'), max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='name',
            field=models.CharField(default='my wallet', max_length=100),
            preserve_default=False,
        ),
    ]
