# Generated by Django 5.1.5 on 2026-07-15 09:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('feature', models.CharField(choices=[('auto_categorize', 'Auto Categorize'), ('receipt_scan', 'Receipt Scan'), ('budget_recommendations', 'Budget Recommendations'), ('chat', 'Chat')], max_length=50)),
                ('input_tokens', models.PositiveIntegerField()),
                ('output_tokens', models.PositiveIntegerField()),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('input_cost', models.DecimalField(decimal_places=8, max_digits=12)),
                ('output_cost', models.DecimalField(decimal_places=8, max_digits=12)),
                ('valid_from', models.DateField()),
            ],
            options={
                'ordering': ['-valid_from'],
                'unique_together': {('provider', 'model', 'valid_from')},
            },
        ),
        migrations.CreateModel(
            name='UserAIQuota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monthly_token_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_quota', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
