# Generated by Django 5.1.5 on 2026-05-11 19:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0008_alter_transaction_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('usd', 'usd'), ('eur', 'eur'), ('gbp', 'gbp'), ('pln', 'pln')], max_length=3)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Every 2 weeks'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('day_of_week', models.IntegerField(blank=True, null=True)),
                ('day_of_month', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('next_occurrence', models.DateField(blank=True, null=True)),
                ('last_processed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_transactions', to='wallets.transactioncategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_transactions', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='recurring_transactions', to='wallets.usertransactiontag')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_transactions', to='wallets.wallet')),
            ],
            options={
                'ordering': ['next_occurrence', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringTransactionExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField()),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('recurring_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='wallets.recurringtransaction')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_source', to='wallets.transaction')),
            ],
            options={
                'ordering': ['-executed_at'],
                'unique_together': {('recurring_transaction', 'scheduled_date')},
            },
        ),
    ]
