# Generated by Django 5.1.5 on 2026-05-13 12:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0009_add_recurring_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_rules', to='wallets.transactioncategory')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_rules', to='wallets.wallet')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='BudgetMonthOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_overrides', to='wallets.transactioncategory')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_overrides', to='wallets.wallet')),
            ],
            options={
                'unique_together': {('wallet', 'category', 'year', 'month')},
            },
        ),
    ]
