# Generated by Django 5.1.5 on 2026-05-13 12:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0010_budgetrule_budgetmonthoverride'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetmonthoverride',
            options={'ordering': ['year', 'month']},
        ),
        migrations.AlterField(
            model_name='budgetmonthoverride',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_overrides', to='wallets.transactioncategory'),
        ),
        migrations.AlterField(
            model_name='budgetmonthoverride',
            name='month',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='budgetrule',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_rules', to='wallets.transactioncategory'),
        ),
    ]
