# Generated by Django 5.1.5 on 2026-05-15 13:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0011_alter_budgetmonthoverride_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_currency', models.CharField(choices=[('usd', 'usd'), ('eur', 'eur'), ('gbp', 'gbp'), ('pln', 'pln')], max_length=3)),
                ('quote_currency', models.CharField(choices=[('usd', 'usd'), ('eur', 'eur'), ('gbp', 'gbp'), ('pln', 'pln')], max_length=3)),
                ('date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12)),
            ],
            options={
                'indexes': [models.Index(fields=['base_currency', 'quote_currency', 'date'], name='wallets_exc_base_cu_dc426d_idx')],
                'unique_together': {('base_currency', 'quote_currency', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred_currency', models.CharField(blank=True, choices=[('usd', 'usd'), ('eur', 'eur'), ('gbp', 'gbp'), ('pln', 'pln')], max_length=3, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
