# Generated by Django 5.1.5 on 2026-05-16 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0012_add_exchange_rate_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transfer_peer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_peer_reverse', to='wallets.transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer_ref',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
